In [1]:
import numpy as np


In [53]:
data = [[[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0]],
        [[0,1,0,0,0],[0,0,1,0,0],[0,1,0,0,0]],          
        [[0,0,1,0,0],[0,1,0,0,0],[1,0,0,0,0]]
       ]

data = np.array(data)
data[0,0]


array([1, 0, 0, 0, 0])

In [58]:

plane=np.zeros((3,3))
for x in range(0,3):
    for y in range(0,3):
        #convd =np.append(convd, np.convolve(data[x,y],data[1,1]))
        #convd.append(np.convolve(data[x,y],data[1,1]))
        convd=np.convolve(data[x,y],data[1,1],mode='same')
        plane[x,y]= 2-np.argmax(convd)
        #print(convd)
        #print(np.argmax(convd)-2)

plane


array([[ 2.,  1.,  0.],
       [ 1.,  0.,  1.],
       [ 0.,  1.,  2.]])

In [31]:
np.convolve?


In [44]:
plane=np.zeros((3,3))
plane               

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [59]:
Z=plane


In [60]:
Z


array([[ 2.,  1.,  0.],
       [ 1.,  0.,  1.],
       [ 0.,  1.,  2.]])

In [61]:
def gaussian_curvature(Z):
    Zy, Zx = np.gradient(Z)
    print(Zy,Zx)
    Zxy, Zxx = np.gradient(Zx)                                                  
    Zyy, _ = np.gradient(Zy)                                                    
    K = (Zxx * Zyy - (Zxy ** 2)) /  (1 + (Zx ** 2) + (Zy **2)) ** 2             
    return K

K = gaussian_curvature(Z)
K

[[-1. -1.  1.]
 [-1.  0.  1.]
 [-1.  1.  1.]] [[-1. -1. -1.]
 [-1.  0.  1.]
 [ 1.  1.  1.]]


array([[ 0.        , -0.11111111, -0.44444444],
       [-0.11111111,  0.        , -0.11111111],
       [-0.44444444, -0.11111111,  0.        ]])

In [51]:
K


array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [ ]:
for x = 